# src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wooden?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: yourpw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always   # schema.sql, data.sql 실행
server:
  port: 8080
